/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint:
    "https://juh3iw4ijvejtheaimud5ldrnq.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-6r5uvniw3bfmfnxli6pfim2h2e",
};

export default awsExports;
